version: '3.8'

services:
  bot1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: ["main", "--dev"]  # 開発モードを追加
    env_file:
      - ../config/.env
    volumes:
      - ../logs:/app/logs
      - ..:/app  # ソースコードの変更を反映するためのボリュームマウント
    environment:
      - BOT_NAME=GPT-4o-animal
      - DISCORD_TOKEN=${DISCORD_TOKEN_BOT1}
      - RESPONSE_PROBABILITY=0.8
    networks:
      - ai-zoo-network

  bot2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: ["secondary", "--dev"]  # 開発モードを追加
    env_file:
      - ../config/.env
    volumes:
      - ../logs:/app/logs
      - ..:/app  # ソースコードの変更を反映するためのボリュームマウント
    environment:
      - BOT_NAME=claude-animal
      - DISCORD_TOKEN=${DISCORD_TOKEN_BOT2}
      - RESPONSE_PROBABILITY=0.7
    networks:
      - ai-zoo-network

  # 追加のボットの設定例
  # 重要: BOT_NAMEはNotionデータベースに登録されているキャラクター名と一致させてください
  # bot3:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   restart: unless-stopped
  #   command: secondary
  #   env_file:
  #     - ../config/.env
  #   volumes:
  #     - ../logs:/app/logs
  #     - ..:/app  # ソースコードの変更を反映するためのボリュームマウント
  #   environment:
  #     - BOT_NAME=new-character-name  # Notionに登録されているキャラクター名
  #     - DISCORD_TOKEN=${DISCORD_TOKEN_BOT3}
  #     - RESPONSE_PROBABILITY=0.6
  #   networks:
  #     - ai-zoo-network

  # Cron service for scheduled messages
  cron:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: cron
    env_file:
      - ../config/.env
    volumes:
      - ../logs:/app/logs
    networks:
      - ai-zoo-network

networks:
  ai-zoo-network:
    driver: bridge
